language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/aliahshakirin/demo-repo2

script:
    - make all_tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: class-demo-repo2
      on:
          branch: master
